[book]
authors = [
  "Jason Lingle",
  "Mazdak Farrokhzad",
  "Matthew Russo"
]
src = "src"
title = "Proptest"
description = "Usage documentation for the family of proptest libraries: proptest, proptest-derive, proptest-macro, and proptest-state-machine"

[output.html]
curly-quotes = true
